POST http://localhost:3000/admin/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:3000/admin/shelter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hZG1pbiI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJGlkSlFsRDNUdVFXOFBCU3pBdHI4N2VSeFpUMDRZelJsdVNIZTlWc0MwY1lvUGVTNWRIRGlHIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzIzMDIyfQ.4vwGhwVT2cGCroLCHG4KGqfn-F9efDftB91j_woiUaM
Content-Type: application/json

{
    "name": "Schronisko dla Zwierząt",
    "login": "shelter",
    "password": "123",
    "city": ""
}

###

