POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "krempa@gmail.com",
    "password": "123",
    "city": "Jedrzejow",
    "firstname": "Maciej",
    "lastname": "Krempa"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "Jakub",
    "password": "1234"
}


###

GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJlbWFpbCI6Impha3ViMjEzeEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Ikpha3ViIiwicGFzc3dvcmQiOiIkMmIkMTAkR0JIeHlrVTh1cGJlZWJYQnlyaTZkT1BPUGpyWld6LzRmMWdNdS9tRC95RHlVdDRFeUwxajIiLCJjaXR5IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzU4MTEyMywiZXhwIjoxNzQ3NTg0NzIzfQ.NhabcuWNu_KEzKV8hMH3yVH_QnhUf8NolDr3nTb-w1M

###

POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
    "email": "jakub213x@gmail.com"
}

###
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
    "password": "1234",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJpYXQiOjE3NDc1ODE0MDQsImV4cCI6MTc0NzU4MjMwNH0.O-CiE01CPTC-BUkAp3R4dg7433xe36RKqRqJwm4fid0"
}