POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin",
    "city": "x",
    "firstname": "x",
    "lastname": "x"
}

###

POST http://localhost:5000/auth/email-verification
Content-Type: application/json

{
    "email": "wwbjjv46hh@jkotypc.com"
}

###

POST http://localhost:5000/auth/email
Content-Type: application/json

{
    "emailToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha3ViMjEzeEBnbWFpbC5jb20iLCJpYXQiOjE3NDg1MTg4NjF9.5yUqW6D6QiR-izy2uN8k1E9bqt4eOVVPVV1GeR38vfs"
}

###

POST http://localhost:5000/auth/register-shelter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJmaXJzdG5hbWUiOiJQb2xhayIsImxhc3RuYW1lIjoiV2llbGtpIiwiY2l0eSI6IldhZG93aWNlIDIxLzM3IiwiZW1haWwiOiJzaGVsdGVyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEg3bURnSktLeFRiRWNjdHFPeUN5OWVuREFkYnNoRUhOOWVqVW5wMVZic2EvL2lTQ0JXMi9LIiwicm9sZSI6InNoZWx0ZXIiLCJpYXQiOjE3NDgxMDAxNzMsImV4cCI6MTc0ODEwMzc3M30.1x3Dl4E4FML0pne3MS9CJunk715-pqFrZ2fzJ3dKK60
Content-Type: application/json

{
    "email": "shelter@gmail.com",
    "password": "123",
    "city": "Wadowice 21/37",
    "firstname": "Polak",
    "lastname": "Wielki"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "jakub213x@gmail.com",
    "password": "123"
}


###

GET http://localhost:5000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxMywiZmlyc3RuYW1lIjoiS3ViYSIsImxhc3RuYW1lIjoiSyIsImNpdHkiOiJSemVzesOzdyIsImVtYWlsIjoiamFrdWIyMTN4QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFdrbEhnbG5qbVlScmtaNlZTNy9UMXVvdnNWWGt6Ui5oOGJzcEpYeDVuM2svUHhraEE4SEJpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDkxNDUzNzJ9.gU9D1lTOq2D0QQidfNblymvaA945z4g6UvXVZV7TH4s

###

POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
    "email": "jakub213x@gmail.com"
}

###
POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
    "password": "1234",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJpYXQiOjE3NDc1ODE0MDQsImV4cCI6MTc0NzU4MjMwNH0.O-CiE01CPTC-BUkAp3R4dg7433xe36RKqRqJwm4fid0"
}

###

GET http://localhost:5000/auth/shelter-accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJmaXJzdG5hbWUiOiJ4IiwibGFzdG5hbWUiOiJ4IiwiY2l0eSI6IngiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEpFVzJ1bTNpejBBbUl1dkNGV1FmUk93aElpSXNrTlVPRzU2QVpEYTF2QUFIRkJCcUxwa1g2Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NjgyOTY5fQ.Bx_7B0GDpr20tWpvP1R00FzxTG5gWzvtipotY8ZRu-w

###

PUT http://localhost:5000/auth/shelter-accounts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJmaXJzdG5hbWUiOiJ4IiwibGFzdG5hbWUiOiJ4IiwiY2l0eSI6IngiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEpFVzJ1bTNpejBBbUl1dkNGV1FmUk93aElpSXNrTlVPRzU2QVpEYTF2QUFIRkJCcUxwa1g2Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ4NjgyOTY5fQ.Bx_7B0GDpr20tWpvP1R00FzxTG5gWzvtipotY8ZRu-w

{
    "firstname": "Jacek",
    "lastname": "Placekk",
    "email": "wa@wp.pl",
    "city": "Poznań"
}

###