POST http://localhost:3000/favourite 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJmaXJzdG5hbWUiOiJNYWNpZWoiLCJsYXN0bmFtZSI6IktyZW1wYSIsImNpdHkiOiJKZWRyemVqb3ciLCJlbWFpbCI6ImtyZW1wYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQxdXpFVDFsa0lVVzM5TzBKdDJzMVhPSzhDZFlTcU1FNnguTFBBOUVydVU2Vy9IMGprZEIvYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MDE5MzU5LCJleHAiOjE3NDgwMjI5NTl9.lj7P1OdJkMVBEdhIlPEWAoaSiiSU9SIpEM-67oDZy1U
Content-Type: application/json

{
    "id_pet": 3
}

###

GET http://localhost:3000/favourite 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJmaXJzdG5hbWUiOiJNYWNpZWoiLCJsYXN0bmFtZSI6IktyZW1wYSIsImNpdHkiOiJKZWRyemVqb3ciLCJlbWFpbCI6ImtyZW1wYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQxdXpFVDFsa0lVVzM5TzBKdDJzMVhPSzhDZFlTcU1FNnguTFBBOUVydVU2Vy9IMGprZEIvYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ4MDE5MzU5LCJleHAiOjE3NDgwMjI5NTl9.lj7P1OdJkMVBEdhIlPEWAoaSiiSU9SIpEM-67oDZy1U
Content-Type: application/json

###