POST http://localhost:5000/favourite 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxMywiZmlyc3RuYW1lIjoiS3ViYSIsImxhc3RuYW1lIjoiSyIsImNpdHkiOiJSemVzesOzdyIsImVtYWlsIjoiamFrdWIyMTN4QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFdrbEhnbG5qbVlScmtaNlZTNy9UMXVvdnNWWGt6Ui5oOGJzcEpYeDVuM2svUHhraEE4SEJpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDkxNDUzNzJ9.gU9D1lTOq2D0QQidfNblymvaA945z4g6UvXVZV7TH4s
Content-Type: application/json

{
    "id_pet": 3
}

###

GET http://localhost:5000/favourite 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxMywiZmlyc3RuYW1lIjoiS3ViYSIsImxhc3RuYW1lIjoiSyIsImNpdHkiOiJSemVzesOzdyIsImVtYWlsIjoiamFrdWIyMTN4QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFdrbEhnbG5qbVlScmtaNlZTNy9UMXVvdnNWWGt6Ui5oOGJzcEpYeDVuM2svUHhraEE4SEJpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDkxNDUzNzJ9.gU9D1lTOq2D0QQidfNblymvaA945z4g6UvXVZV7TH4s
Content-Type: application/json

###